services:
  postgres:
    image: postgres:15-alpine
    container_name: credit_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: risk_database
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: credit_queue
    ports:
      - "5672:5672"   
      - "15672:15672" 
    restart: always

  api-go:
    build: ./api-go
    container_name: credit_api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: always

  worker-python:
    build: ./worker-python
    container_name: credit_worker
    depends_on:
      - rabbitmq
      - postgres
    restart: always

  dashboard:
    build: ./dashboard
    container_name: credit_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    restart: always